************* Module calibration_tool.helpers
calibration_tool/helpers.py:136:0: R0914: Too many local variables (34/15) (too-many-locals)
************* Module calibration_tool.cmd
calibration_tool/cmd.py:38:0: C0301: Line too long (123/100) (line-too-long)
calibration_tool/cmd.py:39:0: C0301: Line too long (146/100) (line-too-long)
calibration_tool/cmd.py:43:0: C0301: Line too long (123/100) (line-too-long)
calibration_tool/cmd.py:179:0: C0325: Unnecessary parens after '=' keyword (superfluous-parens)
calibration_tool/cmd.py:255:0: C0325: Unnecessary parens after '=' keyword (superfluous-parens)
calibration_tool/cmd.py:12:0: C0413: Import "from calibration_tool.calibration.calibration_handling import CalibrationHandler" should be placed at the top of the module (wrong-import-position)
calibration_tool/cmd.py:14:0: C0413: Import "from calibration_tool.logging_config import configure_logging" should be placed at the top of the module (wrong-import-position)
calibration_tool/cmd.py:15:0: C0413: Import "from calibration_tool.exceptions import MissingRequirements" should be placed at the top of the module (wrong-import-position)
calibration_tool/cmd.py:16:0: C0413: Import "from calibration_tool.calibration.calibration_analysis import create_calibration_analysis" should be placed at the top of the module (wrong-import-position)
calibration_tool/cmd.py:18:0: C0413: Import "from calibration_tool.data_integration.data_set import DataSet" should be placed at the top of the module (wrong-import-position)
calibration_tool/cmd.py:28:4: R1720: Unnecessary "else" after "raise", remove the "else" and de-indent the code inside it (no-else-raise)
calibration_tool/cmd.py:191:0: R0914: Too many local variables (19/15) (too-many-locals)
calibration_tool/cmd.py:230:41: R1721: Unnecessary use of a comprehension, use list(disregard_time) instead. (unnecessary-comprehension)
calibration_tool/cmd.py:235:44: R1721: Unnecessary use of a comprehension, use list(coordinate_system.split(',')) instead. (unnecessary-comprehension)
calibration_tool/cmd.py:267:14: R1714: Consider merging these comparisons with 'in' by using 'key in ('intersection_points_xy', 'intersection_points_lonlat')'. Use a set instead if elements are hashable. (consider-using-in)
calibration_tool/cmd.py:191:0: R0912: Too many branches (22/12) (too-many-branches)
calibration_tool/cmd.py:191:0: R0915: Too many statements (60/50) (too-many-statements)
************* Module calibration_tool.optimization
calibration_tool/optimization.py:73:0: R0902: Too many instance attributes (11/7) (too-many-instance-attributes)
calibration_tool/optimization.py:178:0: R0914: Too many local variables (22/15) (too-many-locals)
calibration_tool/optimization.py:192:23: R1721: Unnecessary use of a comprehension, use dict(zip(param_names, params)) instead. (unnecessary-comprehension)
calibration_tool/optimization.py:244:42: W0613: Unused argument 'solution_idx' (unused-argument)
calibration_tool/optimization.py:5:0: W0611: Unused import traceback (unused-import)
************* Module calibration_tool.calibration.calibration_analysis
calibration_tool/calibration/calibration_analysis.py:39:0: C0303: Trailing whitespace (trailing-whitespace)
calibration_tool/calibration/calibration_analysis.py:25:0: C0116: Missing function or method docstring (missing-function-docstring)
calibration_tool/calibration/calibration_analysis.py:31:0: C0116: Missing function or method docstring (missing-function-docstring)
calibration_tool/calibration/calibration_analysis.py:37:8: W0622: Redefining built-in 'id' (redefined-builtin)
calibration_tool/calibration/calibration_analysis.py:37:8: C0103: Variable name "id" doesn't conform to snake_case naming style (invalid-name)
calibration_tool/calibration/calibration_analysis.py:40:0: C0116: Missing function or method docstring (missing-function-docstring)
calibration_tool/calibration/calibration_analysis.py:49:0: C0116: Missing function or method docstring (missing-function-docstring)
calibration_tool/calibration/calibration_analysis.py:50:4: W0612: Unused variable 'eidm0' (unused-variable)
calibration_tool/calibration/calibration_analysis.py:66:0: C0116: Missing function or method docstring (missing-function-docstring)
calibration_tool/calibration/calibration_analysis.py:79:0: C0116: Missing function or method docstring (missing-function-docstring)
calibration_tool/calibration/calibration_analysis.py:83:14: C0103: Variable name "gt" doesn't conform to snake_case naming style (invalid-name)
calibration_tool/calibration/calibration_analysis.py:90:0: C0116: Missing function or method docstring (missing-function-docstring)
calibration_tool/calibration/calibration_analysis.py:97:0: C0116: Missing function or method docstring (missing-function-docstring)
calibration_tool/calibration/calibration_analysis.py:105:0: C0116: Missing function or method docstring (missing-function-docstring)
calibration_tool/calibration/calibration_analysis.py:105:0: R0914: Too many local variables (24/15) (too-many-locals)
calibration_tool/calibration/calibration_analysis.py:137:14: C0103: Variable name "gt" doesn't conform to snake_case naming style (invalid-name)
calibration_tool/calibration/calibration_analysis.py:144:18: C0103: Variable name "gt" doesn't conform to snake_case naming style (invalid-name)
calibration_tool/calibration/calibration_analysis.py:105:0: R0915: Too many statements (53/50) (too-many-statements)
calibration_tool/calibration/calibration_analysis.py:192:0: R0914: Too many local variables (20/15) (too-many-locals)
calibration_tool/calibration/calibration_analysis.py:14:0: C0411: standard import "import shutil" should be placed before "import matplotlib.backends.backend_pdf" (wrong-import-order)
calibration_tool/calibration/calibration_analysis.py:5:0: W0611: Unused import logging (unused-import)
calibration_tool/calibration/calibration_analysis.py:7:0: W0611: Unused import sys (unused-import)
************* Module calibration_tool.calibration.calibration_handling
calibration_tool/calibration/calibration_handling.py:24:0: C0413: Import "from calibration_tool.data_integration.case_identification import car_at_redlight, following_cars" should be placed at the top of the module (wrong-import-position)
calibration_tool/calibration/calibration_handling.py:26:0: C0413: Import "from calibration_tool.data_integration.data_set import DataSet" should be placed at the top of the module (wrong-import-position)
calibration_tool/calibration/calibration_handling.py:27:0: C0413: Import "from calibration_tool.exceptions import InvalidOptions" should be placed at the top of the module (wrong-import-position)
calibration_tool/calibration/calibration_handling.py:28:0: C0413: Import "from calibration_tool.fileaccess.parameter import EidmParameters, Parameters" should be placed at the top of the module (wrong-import-position)
calibration_tool/calibration/calibration_handling.py:29:0: C0413: Import "from calibration_tool.logging_config import configure_logging" should be placed at the top of the module (wrong-import-position)
calibration_tool/calibration/calibration_handling.py:30:0: C0413: Import "from calibration_tool.models.models import TrafficFollowingModel" should be placed at the top of the module (wrong-import-position)
calibration_tool/calibration/calibration_handling.py:31:0: C0413: Import "from calibration_tool.optimization import CounterHandler, TargetCollector, functional_target, target_factory" should be placed at the top of the module (wrong-import-position)
calibration_tool/calibration/calibration_handling.py:35:0: C0413: Import "from calibration_tool.sumo.sumo_interface import SumoInterface" should be placed at the top of the module (wrong-import-position)
calibration_tool/calibration/calibration_handling.py:36:0: C0413: Import "from calibration_tool.sumo.sumo_project import SumoProject" should be placed at the top of the module (wrong-import-position)
calibration_tool/calibration/calibration_handling.py:37:0: C0413: Import "from calibration_tool.calibration.calibration_analysis import create_calibration_analysis" should be placed at the top of the module (wrong-import-position)
calibration_tool/calibration/calibration_handling.py:39:0: C0413: Import "from calibration_tool.helpers import _estimate_parameters, _get_data_chunk" should be placed at the top of the module (wrong-import-position)
calibration_tool/calibration/calibration_handling.py:48:0: R0902: Too many instance attributes (24/7) (too-many-instance-attributes)
calibration_tool/calibration/calibration_handling.py:51:4: R0913: Too many arguments (10/6) (too-many-arguments)
calibration_tool/calibration/calibration_handling.py:210:4: R0914: Too many local variables (21/15) (too-many-locals)
calibration_tool/calibration/calibration_handling.py:346:4: R0914: Too many local variables (17/15) (too-many-locals)
calibration_tool/calibration/calibration_handling.py:372:20: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
calibration_tool/calibration/calibration_handling.py:421:4: R0914: Too many local variables (21/15) (too-many-locals)
calibration_tool/calibration/calibration_handling.py:422:8: W0603: Using the global statement (global-statement)
calibration_tool/calibration/calibration_handling.py:423:8: W0603: Using the global statement (global-statement)
calibration_tool/calibration/calibration_handling.py:577:27: R1721: Unnecessary use of a comprehension, use dict(zip(self.param_keys, params)) instead. (unnecessary-comprehension)
calibration_tool/calibration/calibration_handling.py:20:0: C0411: standard import "import shutil" should be placed before "import numpy as np" (wrong-import-order)
calibration_tool/calibration/calibration_handling.py:19:0: W0611: Unused argrelextrema imported from scipy.signal (unused-import)
************* Module calibration_tool.models.models
calibration_tool/models/models.py:5:0: W0611: Unused numpy imported as np (unused-import)
calibration_tool/models/models.py:6:0: W0611: Unused pandas imported as pd (unused-import)
calibration_tool/models/models.py:9:0: W0611: Unused following_cars imported from calibration_tool.data_integration.case_identification (unused-import)
calibration_tool/models/models.py:9:0: W0611: Unused euclidian_distance imported from calibration_tool.data_integration.case_identification (unused-import)
************* Module calibration_tool.data_integration.integrator
calibration_tool/data_integration/integrator.py:101:0: C0303: Trailing whitespace (trailing-whitespace)
calibration_tool/data_integration/integrator.py:105:0: C0304: Final newline missing (missing-final-newline)
calibration_tool/data_integration/integrator.py:17:0: R0902: Too many instance attributes (14/7) (too-many-instance-attributes)
calibration_tool/data_integration/integrator.py:99:4: C0116: Missing function or method docstring (missing-function-docstring)
************* Module calibration_tool.data_integration.data_set
calibration_tool/data_integration/data_set.py:52:4: R0914: Too many local variables (36/15) (too-many-locals)
calibration_tool/data_integration/data_set.py:61:8: R1703: The if statement can be replaced with 'var = bool(test)' (simplifiable-if-statement)
calibration_tool/data_integration/data_set.py:52:4: R0912: Too many branches (27/12) (too-many-branches)
calibration_tool/data_integration/data_set.py:52:4: R0915: Too many statements (71/50) (too-many-statements)
calibration_tool/data_integration/data_set.py:207:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
calibration_tool/data_integration/data_set.py:218:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
calibration_tool/data_integration/data_set.py:267:4: R0913: Too many arguments (12/6) (too-many-arguments)
calibration_tool/data_integration/data_set.py:283:17: R1735: Consider using '{"data_file_regex": data_file_regex, "skip_corrupt": skip_corrupt}' instead of a call to 'dict'. (use-dict-literal)
************* Module calibration_tool.data_integration.case_identification
calibration_tool/data_integration/case_identification.py:33:0: R0914: Too many local variables (49/15) (too-many-locals)
calibration_tool/data_integration/case_identification.py:33:0: R0912: Too many branches (24/12) (too-many-branches)
calibration_tool/data_integration/case_identification.py:33:0: R0915: Too many statements (92/50) (too-many-statements)
calibration_tool/data_integration/case_identification.py:187:0: R0914: Too many local variables (16/15) (too-many-locals)
calibration_tool/data_integration/case_identification.py:10:0: C0411: standard import "from collections import Counter" should be placed before "import numpy as np" (wrong-import-order)
************* Module calibration_tool.data_integration.helper
calibration_tool/data_integration/helper.py:11:4: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
calibration_tool/data_integration/helper.py:9:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
calibration_tool/data_integration/helper.py:19:19: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
calibration_tool/data_integration/helper.py:19:22: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
calibration_tool/data_integration/helper.py:41:0: R0914: Too many local variables (16/15) (too-many-locals)
calibration_tool/data_integration/helper.py:71:16: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
calibration_tool/data_integration/helper.py:71:31: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
calibration_tool/data_integration/helper.py:97:0: C0116: Missing function or method docstring (missing-function-docstring)
calibration_tool/data_integration/helper.py:108:9: C0103: Variable name "up" doesn't conform to snake_case naming style (invalid-name)
calibration_tool/data_integration/helper.py:6:0: W0611: Unused scipy imported as sp (unused-import)
calibration_tool/data_integration/helper.py:7:0: W0611: Unused scipy.interpolate imported as ip (unused-import)
************* Module calibration_tool.sumo.sumo_project
calibration_tool/sumo/sumo_project.py:254:0: C0304: Final newline missing (missing-final-newline)
calibration_tool/sumo/sumo_project.py:61:15: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
calibration_tool/sumo/sumo_project.py:76:4: R0914: Too many local variables (19/15) (too-many-locals)
calibration_tool/sumo/sumo_project.py:170:15: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
************* Module calibration_tool.sumo.sumo_interface
calibration_tool/sumo/sumo_interface.py:48:0: R0902: Too many instance attributes (13/7) (too-many-instance-attributes)
calibration_tool/sumo/sumo_interface.py:104:16: R1721: Unnecessary use of a comprehension, use list(self.data_dir.glob('*selection.csv')) instead. (unnecessary-comprehension)
calibration_tool/sumo/sumo_interface.py:51:4: R0915: Too many statements (57/50) (too-many-statements)
calibration_tool/sumo/sumo_interface.py:141:20: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
calibration_tool/sumo/sumo_interface.py:148:12: W0621: Redefining name 'traci' from outer scope (line 28) (redefined-outer-name)
calibration_tool/sumo/sumo_interface.py:148:12: C0415: Import outside toplevel (traci) (import-outside-toplevel)
calibration_tool/sumo/sumo_interface.py:182:4: R0914: Too many local variables (17/15) (too-many-locals)
calibration_tool/sumo/sumo_interface.py:212:16: W0621: Redefining name 'data' from outer scope (line 694) (redefined-outer-name)
calibration_tool/sumo/sumo_interface.py:239:4: R0914: Too many local variables (17/15) (too-many-locals)
calibration_tool/sumo/sumo_interface.py:292:4: R0914: Too many local variables (45/15) (too-many-locals)
calibration_tool/sumo/sumo_interface.py:292:4: R0915: Too many statements (77/50) (too-many-statements)
calibration_tool/sumo/sumo_interface.py:508:12: W0612: Unused variable 'init_distance' (unused-variable)
calibration_tool/sumo/sumo_interface.py:661:15: W0718: Catching too general exception Exception (broad-exception-caught)
calibration_tool/sumo/sumo_interface.py:586:8: W0201: Attribute 'step_results' defined outside __init__ (attribute-defined-outside-init)
calibration_tool/sumo/sumo_interface.py:675:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
calibration_tool/sumo/sumo_interface.py:688:4: W0404: Reimport 'logging' (imported line 4) (reimported)
calibration_tool/sumo/sumo_interface.py:689:4: W0404: Reimport 'os' (imported line 5) (reimported)
calibration_tool/sumo/sumo_interface.py:688:4: C0412: Imports from package logging are not grouped (ungrouped-imports)
calibration_tool/sumo/sumo_interface.py:689:4: C0412: Imports from package os are not grouped (ungrouped-imports)
calibration_tool/sumo/sumo_interface.py:21:0: W0611: Unused _rescale_to_n imported from calibration_tool.helpers (unused-import)

------------------------------------------------------------------
Your code has been rated at 9.47/10 (previous run: 9.47/10, +0.00)

